# Overrides upstream Caelestia hypr/variables.conf defaults after install.

$terminal = kitty
$browser = firefox
$editor = $cConf/scripts/cursor-clean.sh
$fileExplorer = $HOME/.config/caelestia/scripts/nautilus-wrap.sh
$cursorTheme = capitaine-cursors
