#!/usr/bin/env bash
# Emit bindnitn lines so caelestia:launcherInterrupt runs alongside every Super chord
# (Hypr catchall alone does not fire when the key already has a Super bind).
set -euo pipefail

out="${1:-${HOME}/.config/caelestia/hypr-launcher-interrupts.conf}"
mkdir -p "$(dirname "$out")"

python3 - "$out" <<'PY'
import json, subprocess, sys

out_path = sys.argv[1]
raw = subprocess.check_output(["hyprctl", "binds", "-j"], text=True)
binds = json.loads(raw)

SKIP_KEYS = frozenset({"Super_L", "Super_R", ""})
SKIP_ARGS = frozenset({
    "caelestia:launcher",
    "caelestia:launcherArm",
    "caelestia:launcherInterrupt",
})

# Hypr modmask bits (clear bit 1 — spurious in some binds)
BIT_CTRL, BIT_SHIFT, BIT_ALT, BIT_SUPER = 4, 8, 2, 64
ORDER = [
    (BIT_CTRL, "Ctrl"),
    (BIT_SHIFT, "Shift"),
    (BIT_ALT, "Alt"),
    (BIT_SUPER, "Super"),
]


def mod_string(mask: int) -> str:
    m = mask & ~1
    parts = [name for bit, name in ORDER if m & bit]
    return "+".join(parts)


seen: set[tuple[int, str]] = set()
lines: list[str] = []

for b in binds:
    mask = int(b.get("modmask") or 0)
    if not (mask & BIT_SUPER):
        continue
    key = (b.get("key") or "").strip()
    if key in SKIP_KEYS or b.get("catch_all"):
        continue
    arg = (b.get("arg") or "").strip()
    if arg in SKIP_ARGS:
        continue
    pair = (mask, key)
    if pair in seen:
        continue
    seen.add(pair)
    mods = mod_string(mask)
    lines.append(f"bindnitn = {mods}, {key}, global, caelestia:launcherInterrupt")

lines.sort()
with open(out_path, "w", encoding="utf-8") as f:
    f.write("# Generated by gen-hypr-launcher-interrupts.sh — do not edit\n")
    f.write(f"# {len(lines)} explicit Super-chord interrupts\n\n")
    f.write("\n".join(lines))
    f.write("\n")

print(f"Wrote {len(lines)} interrupt binds to {out_path}")
PY
